#!/bin/sh
STATUS=1
# Check sources can be compiled.
tsc --noEmit --skipLibCheck
STATUS=$?
if [ $STATUS -ne 0 ]
then
  exit 1
fi

STATUS=1
# Lint the codebase.
npm run lint
STATUS=$?
if [ $STATUS -ne 0 ]
then
  exit 1
fi